### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by bug-author** [shy-tan/aura#1]
- [x] change bg dynamically
- [x] time
- [x] learn Tailwind Css lmao
- [x] one/ two bg(s) every 24/ 12 hrs
- [x] greeting
- [x] home-page
- [x] weather
- [x] favorites
- [x] mockup
- [x] hover favs
- [x] quote of the day
